# Generated by Django 2.1.3 on 2018-12-25 09:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, help_text='是否热门', verbose_name='是否热门'),
        ),
        migrations.AlterField(
            model_name='article',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 25, 9, 25, 39, 866459), help_text='发布日期', verbose_name='发布日期'),
        ),
    ]
