# Generated by Django 2.1.3 on 2019-01-07 12:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20181225_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 7, 12, 15, 2, 113297), help_text='发布日期', verbose_name='发布日期'),
        ),
    ]
