# Generated by Django 2.0.2 on 2019-02-13 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actice',
            name='datetime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterModelTable(
            name='actice',
            table='actice',
        ),
    ]
