# Generated by Django 2.0.2 on 2019-02-13 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actice', '0002_auto_20190213_0935'),
    ]

    operations = [
        migrations.CreateModel(
            name='aaa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='bbb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tile', models.CharField(max_length=50)),
                ('con', models.TextField()),
                ('aa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actice.aaa')),
            ],
        ),
    ]
