# Generated by Django 2.0.2 on 2019-04-18 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0002_user_nickname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='openid',
        ),
    ]
