#-*- coding: utf-8 -*-
from django.db import models

# Create your models here.
# class fuwuqi1(models.Model):
#     ID=models.IntegerField()
#     GAME_DB_NAME= models.CharField(max_length=200)
#     GAME_ID = models.IntegerField()
#     GAME_DESC=models.CharField(max_length=200)
#     GAME_NAME = models.CharField(max_length=200)
#     GATEWAY_ID = models.IntegerField()
#     GATEWAY =models.CharField(max_length=200)
#     ALL_GAME = models.CharField(max_length=200)
#     SERVER_ID=models.CharField(max_length=200)
#     DESCRIPTION=models.CharField(max_length=200)
#     OPEN_DATE=models.CharField(max_length=200)
#     DB_NUMBER=models.CharField(max_length=200)
#     ZONE_ID=models.IntegerField()
#     ZONE_NAME=models.CharField(max_length=200)
#     PAY_MODULE=models.CharField(max_length=200)
#     N_DAYS=models.IntegerField()
#     class Meta:
#         db_table='FUWUQI_TABLE'
# class jx3_role_log_opeartion(models.Model):
#     RECORD_DATE=models.DateField()
#     DBNAME =models.CharField(max_length=200)
#     ACCOUNTNAME = models.CharField(max_length=200)
#     ROLENAME= models.CharField(max_length=200)
#     ROLEID=models.IntegerField()
#     DEL_GLOBALROLEID=models.IntegerField()
#     ACTIONTYPE=models.IntegerField()
#     COL_1= models.CharField(max_length=400)
#     COL_2= models.CharField(max_length=400)
#     COL_3= models.CharField(max_length=400)
#     COL_4= models.CharField(max_length=400)
#     COL_5= models.CharField(max_length=400)
#     COL_6= models.CharField(max_length=400)
#     COL_7= models.CharField(max_length=400)
#     COL_8= models.CharField(max_length=400)
#     COL_9= models.CharField(max_length=400)
#     COL_10= models.CharField(max_length=400)
#     COL_11= models.CharField(max_length=400)
#     COL_12= models.CharField(max_length=400)
#     COL_13= models.CharField(max_length=400)
#     COL_14= models.CharField(max_length=400)
#     COL_15= models.CharField(max_length=400)
#     COL_16= models.CharField(max_length=400)
#     COL_17= models.CharField(max_length=400)
#     COL_18= models.CharField(max_length=400)
#     COL_19= models.CharField(max_length=400)
#     COL_20= models.CharField(max_length=400)
#     COL_21= models.CharField(max_length=400)
#     COL_22= models.CharField(max_length=400)
#     COL_23= models.CharField(max_length=400)
#     COL_24= models.CharField(max_length=400)
#     COL_25= models.CharField(max_length=400)
#     COL_26= models.CharField(max_length=400)
#     COL_27= models.CharField(max_length=400)
#     COL_28= models.CharField(max_length=400)
#     COL_29= models.CharField(max_length=400)
#     COL_30= models.CharField(max_length=400)
#     COL_31= models.CharField(max_length=400)
#     COL_32= models.CharField(max_length=400)
#     COL_33= models.CharField(max_length=400)
#     GLOBALROLEID= models.CharField(max_length=200)
#     class Meta:
#         db_table='xsjods.jx3_role_log_opeartion'
class renwu_shuju(models.Model):
    id=models.IntegerField(primary_key=True,db_column='ID')
    D_BNAME= models.CharField(max_length=200,null=False)
    ACCOUNTNAME= models.CharField(max_length=200,null=False)
    DBNAME= models.CharField(max_length=200,null=False)
    ROLENAME= models.CharField(max_length=200,null=False)
    RENWUSHU=models.IntegerField(null=False)
    ROLEID=models.IntegerField(null=False)
    TAG= models.CharField(max_length=200,null=False)
    TONGBAO=models.IntegerField(null=False)
    TIME=models.IntegerField(null=False)
    TBCOST=models.IntegerField(null=False)
    BIAOJI= models.CharField(max_length=200,null=False)
    ALLTIME=models.IntegerField(null=False)
    ROLE_TYPE= models.CharField(max_length=200,null=False)
    DLTAG= models.CharField(max_length=200,null=False)
    ZBFS=models.IntegerField(null=False)
    ZDJL=models.IntegerField(null=False)
    ZDXQ=models.IntegerField(null=False)
    JLDJ= models.CharField(max_length=200,null=False)
    XQDJ= models.CharField(max_length=200,null=False)

    class Meta:
        db_table='renwu'